######################## default configuration ####################
#baseURL = "http://localhost:1313/"
baseURL = "https://oscar.grycap.net"
title = "OSCAR"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalyticsID = "G-902S7WV6RK" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
disableLanguages = ["De"]


[params]
   [params.favicon]
       href = "/favicon.ico"       
       type = "image/x-icon"