#################### default parameters ################################
logo = "images/oscar3-logo-trans.png"
logo_width = "200px"
# Meta data
description = "OSCAR: Open Source Serverless Computing for Data-Processing Applications"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "GitHub"
link = "https://github.com/grycap/oscar"



#thanks


[[thanks]]
label="thanks to AEI"
logo="images/logo-AEI.svg"
width="120"
height="120"
[[thanks]]
label="thanks to gob"
logo="images/logo-gob.svg"
width="120"
height="120"
[[thanks]]
label="thanks to sci"
logo="images/logo-ministerio-ciencia.svg"
width="70"
height="70"

[[thanks]]
label="thanks to EU"
logo="images/logo-nextgen.png"
width="150"
height="50"
[[thanks]]
label="thanks to PRTR2"
logo="images/logo-PRTR2.png"
width="120"
height="50"


[[thankscommentary]]
content="Proyecto PDC2021-120844-I00  financiado por Ministerio de Ciencia e Innovación, Agencia Estatal de Investigación/10.13039/501100011033 y por la Unión Europea “NextGenerationEU”/PRTR."

[[thankscommentary]]
content="Proyecto PID2020-113126RB-I00  financiado por Ministerio de Ciencia e Innovación, Agencia Estatal de Investigación/10.13039/501100011033"



############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "GitHub"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/grycap/oscar"



#[[social]]
#title = "skype"
#icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"
