#################### default parameters ################################
logo = "images/oscar3-logo-trans.png"
logo_width = "200px"
# Meta data
description = "OSCAR: Open Source Serverless Computing for Data-Processing Applications"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "GitHub"
link = "https://github.com/grycap/oscar"



#agradecimientos


[[thanks]]
label="Los agradecimientos"
logo="images/logo-AEI.svg"
width="120"
height="120"
[[thanks]]
label="Los agradecimientos2"
logo="images/logo-gob.svg"
width="120"
height="120"
[[thanks]]
label="Los agradecimientos2"
logo="images/logo-ministerio-ciencia.svg"
width="70"
height="70"

[[thanks]]
label="Los agradecimientos2"
logo="images/logo-nextgen.png"
width="150"
height="50"
[[thanks]]
label="Los agradecimientos2"
logo="images/logo-PRTR2.png"
width="120"
height="50"

#Elegir uno de los dos siguientes

#[[thankscommentary]]
#content="Este resultado es parte del proyecto de I+D+i 'Referencia del proyecto', financiado por MCIN/AEI/10.13039/501100011033/ y Financiado por la Unión Europea “NextGenerationEU”/PRTR."

[[thankscommentary]]
#PDC2021-120844-I00
content="Proyecto 'Referencia del/de la proyecto/ayuda'  financiado por Ministerio de Ciencia e Innovación, Agencia Estatal de Investigación/10.13039/501100011033 y por la Unión Europea “NextGenerationEU”/PRTR."
#[[thankscommentary]]
#content="Ayuda 'Referencia de la ayuda' financiada por: Ministerio de Ciencia e Innovación, Agencia Estatal de Investigación, Financiado por la Unión Europea 'NextGenerationEU', y Plan de Recuperación,Transformación y Resiliencia(PRTR) "

#[[thankscommentary]]
#content="Ayuda Referencia de la ayuda financiada por: logotipo MCIN, logotipo AEI"

#Confirmar
#[[thankscommentary]]
#content="Ayuda Referencia de la ayuda financiada por: logotipo MCIN, logotipo FEDER “Una manera de hacer Europa”, logotipo AEI."

#[[thankscommentary]]
#content="Ayuda Referencia de la ayuda financiada por: logotipo MCIN, logotipo FSE “El FSE invierte en tu futuro”, logotipo AEI."

#[[thankscommentary]]
#content="Ayuda Referencia de la ayuda financiada por: logotipo MCIN, logotipo “Financiado por la Unión Europea “NextGenerationEU”, logotipo PRTR, logotipo AEI."


#[thanksgiven]
#enable=true
#label="Los agradecimientos3"
#logo="images/logo-AEI.svg"
#width="20%"
#height="20%"

############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "GitHub"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/grycap/oscar"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/gmolto"

#[[social]]
#title = "skype"
#icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[social]]
#title = "linkedin"
#icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"
